services:
  api:
    build:
      context: ./apps/api
    container_name: mini-reto-api
    restart: unless-stopped
    environment:
      PORT: 3001
      GITHUB_API_BASE_URL: ${GITHUB_API_BASE_URL:-https://api.github.com}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3001/user/octocat"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./apps/web
      args:
        NEXT_PUBLIC_API_URL: http://api:3001
        NEXT_PUBLIC_GITHUB_USERNAME: ${NEXT_PUBLIC_GITHUB_USERNAME:-bramirezjofre}
    container_name: mini-reto-web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:3000"
